refactoring devops
xLydianSoftware/Qubx pull request #14
Opened 2024-12-20 18:23 UTC by Tzumx

2024-12-21 10:59 UTC, yuriy-arabskyy commented on src/qubx/utils/runner.py
> +    symbols: list[str | Instrument],
let's just keep a list of string symbols, because we anyway have an exchange name above

2024-12-21 11:01 UTC, yuriy-arabskyy commented on src/qubx/utils/runner.py
> +class StrategyConfig:
why don't we use pydantic classes and parse from dictionary? It will throw an exception if the config is invalid

2024-12-21 11:03 UTC, yuriy-arabskyy commented on src/qubx/utils/runner.py
> +    instruments: list[Instrument] | None = None
same thing, let's use pydantic. And also in the config we should provide a list of symbols and not instrument objects. Instruments should then be constructed later

2024-12-21 11:09 UTC, dmarienko requested changes

2024-12-21 11:09 UTC, dmarienko commented on src/qubx/utils/runner.py
>          content = yaml.safe_load(f)
I'd also propose to handle exceptions here - if config file doesn't have valid yml  structure it'd be  convenient if we see appropriate error message.

2024-12-21 11:09 UTC, dmarienko commented on src/qubx/utils/runner.py
> +        strategy: IStrategy,
May be we could pass here only StrategyConfig and instantiate IStrategy inside this method ? It'd give us more flexibility in using create_strategy_context method ?

2024-12-21 11:11 UTC, yuriy-arabskyy commented on src/qubx/utils/runner.py
> +    strategy: str
also we reviewed the strategy configuration and decided that this definition will be better https://www.notion.so/Qubx-strategy-config-description-15f26136e24480bfa3d5e444eea7d898?pvs=4 so please update like this

2024-12-21 11:13 UTC, yuriy-arabskyy commented on src/qubx/utils/runner.py
>  def create_strategy_context(
could you reuse this method in the runner? We could completely remove the run_ccxt_paper and have this unified construction of context

2024-12-21 11:16 UTC, yuriy-arabskyy commented on src/qubx/utils/runner.py
> +    strategy, cfg = get_strategy(filename, paths, account, acc_config["exchange"])
regarding exchange, for running momentix I had to hardcode a fix so that we trade on BINANCE.PM (portfolio margin) and perpetual symbols are fed in (constructing instruments via BINANCE.UM). @dmarienko we have to handle this somehow properly in the configuration. And I'm not sure yet what is the best way.

2024-12-21 11:16 UTC, yuriy-arabskyy commented on src/qubx/utils/runner.py
>              run_ccxt_trading(
here I would prefer to create a context object and then run it, instead of doing a match like this

2024-12-21 12:01 UTC, yuriy-arabskyy commented
Also please cover config parsing with unit tests and example configs

2024-12-22 11:57 UTC, dmarienko commented on src/qubx/utils/runner.py
Also @Tzumx could you use parameters declarations in function's definitions -`get_ccxt_instances(account_id: str, base_currency: str, ....` ?

2024-12-22 12:00 UTC, yuriy-arabskyy commented on src/qubx/utils/runner.py
and in general, I don't like these vague method names like `get_strategy_data` or `get_ccxt_instances` because you don't know what they do unless you go through their implementation. I would prefer something more understandable and potentially decomposing into multiple methods.

2024-12-24 09:12 UTC, dmarienko commented on src/qubx/utils/runner.py
> +    if "exchange" not in [k.lower() for k in account_data.keys()]:
Why do we use such weird notation like accountid__xxx for config ?
Why not use standard config files like:
```
[account1]
key=...
secret=...
any_other_param=...
```

2024-12-24 09:12 UTC, dmarienko commented on src/qubx/utils/runner.py
> +            account, broker, data_provider = initialize_ccxt_components(
It's not connected to exchange on this step yet.

2024-12-26 21:52 UTC, merged